# Generated by Django 3.1.7 on 2021-06-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_question', to='posting.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='ip_question', to='posting.Ip'),
        ),
    ]
