# Generated by Django 3.1.7 on 2021-06-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_answer_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
    ]
